source 'https://rubygems.org'
gem 'rails', '4.1.4'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'pg'
gem 'unicorn'
gem 'foreman'
gem 'gcm'
gem 'haml'
gem 'haml-rails'
gem 'delayed_job_active_record'
gem 'therubyracer'
gem 'figaro'
gem 'daemons'
gem 'newrelic_rpm'
